### ISSUE TITLE
Clearer command naming

### ISSUE THREAD

**Issue by jclsn** [luochen1990/rainbow#193]
First of all, thank you for improving the old rainbow plugin. This one works much better. 

I think the naming of the commands for toggling the rainbow colors is not optimal. While it is not wrong to say toggling something on/off, in software development this is not how the word is used. It means if something is already in the on state, it should get turned off and when something is in the off state, it should get turned on. 

When you toggle, you switch the state - no matter which state it was in before.

So I think it would be clearer (and shorter) to rename the commands as follows:

RainbowToggleOn -> RainbowOn
RainbowToggleOff -> RainbowOff
RainbowToggle -> can stay unchanged

**Comment by luochen1990** [comment]
Thanks for your suggestion.  I think you are right since it is about English and that's not my best.   but these two command are rarely typed by people, and considering the usage situation:

1) If you want to temporary toggle this plugin, use `RainbowToggle` is enough.
2) If it is used in some VimL scripts, then what they typed like is not the most important thing, but keeping them not changed is much more important and cause less issues.

So, I think keep them not changed might be the best solution for now  :)   and thanks for your suggestion again.
