### ISSUE TITLE
Plugin breaks ai

### ISSUE THREAD

**Issue by jljucutan** [luochen1990/rainbow#20]
autoindent deactivates when this plugin gets activated.
Steps to reproduce:
1. Add let g:rainbow_active = 1 to .vimrc
2. Open a file, say controller.php
3. Create a class, open a curly brace then hit enter
4. Cursor should be indented but it's not
5. You have to :set ai or :set autoindent to make it work again although it's already in .vimrc
6. Setting rainbow_active to 0 seems to temporarily fix the issue

**Comment by userid** [comment]
+1
Yes, the same problem to me on `php`.
It works well on java.

**Comment by ollmer** [comment]
+1, same problem with perl file. Also, i had the same problem with other rainbow parentheses plugin from kien.

**Comment by purbam** [comment]
+1
Got the same problem here.
The plugin works well for some languages, like Python, but breaks the indent for some others like Perl, C-Shell. And the weird thing is, even in the same language, some indents still work, but some are broken. For example, in Perl, below codes have correct indent,
sub test {
    correct indent;
}
But, it's broken in "if" block,
if ($test) {
incorrect indent;
}

I have tried to remove all the other plugins, and just used rainbow with "set ai" in .vimrc, the problem is still there. It can be reproduced by "vim test.pl" and just typing above codes in.

**Comment by wangvisual** [comment]
+1 for perl
Just my guess, It might caused by this plugin create new syntax region:
let def_rg = 'syn region %s matchgroup=%s containedin=%s contains=%s,@NoSpell %s'

And the code before & after the region was in original syntax, eg perl, but the code within the region(like '{') is another syntax, that might break auto indent.

**Comment by kaiyulee** [comment]
+1 , 我之前用kien的貌似没出问题。然后更新了下，发现缩进挂了。我在StackOverflow上提问了，然后发现是插件的原因。

Question on [StackOverflow](http://stackoverflow.com/questions/36771874/vim-curly-brace-indent-incorrectly?noredirect=1#comment61121839_36771874)

**Comment by doy** [comment]
the problem is that by default, perl (and probably others) use the results of syntax highlighting in their indent files - see the definition for perl here https://github.com/vim/vim/blob/master/runtime/indent/perl.vim#L117-L154 . when the rainbow plugin changes the highlight of the brace, the indent file no longer detects it as a valid thing to indent for, and so auto-indentation breaks.

perl's indent file allows you to work around this on your own by something like `autocmd BufEnter <buffer> let b:indent_use_syntax = 0` to disable syntax-based indentation, although that might make autoindent not work as well in some cases. it doesn't look like the php indent file has an equivalent, unfortunately.

this plugin could maybe do something where it detects the current filetype and changes the syntax id prefix from `rainbow` to something like `perlBlockFoldRainbow` or `phpBlockRainbow` or something like that (since most of the places where it's switching on syntax group name seem to happen to include a regex-based prefix check for at least one option), but that seems like a lot of effort, and pretty fragile, and not really guaranteed to be possible or work correctly in all cases either.

**Comment by luochen1990** [comment]
This seems not easy to solve, maybe you can use the following configuration to disable rainbow for perl:

```
	let s:rainbow_conf = {
	\	'separately': {
	\		'perl': 0,
	\	}
	\}
```

Or if you still want rainbow works for `()` and `[]`, you can use the following configuration:
```
	let s:rainbow_conf = {
	\	'separately': {
	\		'perl': {
	\			'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold'],
	\		},
	\	}
	\}
```
