### ISSUE TITLE
Feature Request: C++ Specific Highlighting

### ISSUE THREAD

**Issue by bhilburn** [luochen1990/rainbow#23]
Hey @luochen1990 - 

Really enjoying the plugin!

A couple of feature requests:

1) It would be great if '<' and '>' could be highlighted correctly in C++. Kien's plugin is actually able to do this successfully, but it is no longer maintained. 

Plugin: https://github.com/kien/rainbow_parentheses.vim

```
:RainbowParenthesesLoadChevrons " <>
```

The issue is that if I add them to this plugin, it gets confused in streams. Example:

```
std::cout << "This is a printout to standard out." << std::end;
```

This plugin will incorrectly interpret each '<' as an opening brace and assign it a different color.

2) @oblitum's plugin (abandoned) also highlights namespace delimiters, which would be awesome to add to this. Specifically, I'm referring to the '::' operator.

``` cpp
     namespace top::next::name;
```

3) Lastly, can you update the docs with an example of operator highlighting? I'm a bit confused regarding how to do that properly.

Again, these are all feature requests. Thanks for your hardwork @luochen1990!

**Comment by sicr0** [comment]
@mwnx sorry for joining so late. I tought that since I always use spaces around operators, for me having no space after '<' should be enough to trigger the match. I tried to decipher your regex but I can't actually understand how to do this. Could you please help me or pointing me to some useful resource?
