### ISSUE TITLE
other forks of kien's rainbow parentheses

### ISSUE THREAD

**Issue by Konfekt** [luochen1990/rainbow#27]
There is now

https://github.com/junegunn/rainbow_parentheses.vim

that also forks kien's rainbow parentheses and also simplified it. 

It would be interesting to compare these two.

**Comment by luochen1990** [comment]
yeah. there is a lot of implimentation of rainbow parentheses, but they all leaves some problems to user, which should be solved by the plugin:
1. the maxlevel of parentheses should be designated by user, which should be unlimited automaticly.
2. the number of colors used in GUI and TERM should be equal, which is unreasonable for user.
3. the length of syntax rules generated by this plugin should not be unlimited large when the maxlevel of parentheses is unlimited.
4. the types of parentheses is selected from a few ones. which should be configurable by users themself.
that's why i created this plugin.

i still want listen to your comparation :)

**Comment by Konfekt** [comment]
Ok, 

I didn't know that even the most recent forks suffer from thr defects you listed. 

The only gripe that I had with your plugin is that on various text file types such as txt or tex, the spell check Highlight broke. 

Is that a side effect of resolving point 2?

**Comment by luochen1990** [comment]
yeah, there are problems, but I'm tring to fix them all, the spell checking problem you talked about is solved recently, see #24 for details.

**Comment by Konfekt** [comment]
Yep, I opened it for TeX (in https://github.com/luochen1990/rainbow/issues/17) and Text filetypes and you solved it :+1:  However, now I'm afraid that for other filetypes the issue reoccurs.

This is a nasty bug because hard to trace down and pehaps even goes by unnoticed.
