### ISSUE TITLE
Parens for inline javascript callbacks are not highlighted properly

### ISSUE THREAD

**Issue by meuserj** [luochen1990/rainbow#44]
As per the below screenshot, anonymous javascript functions passed into a function call do not appear to have the parenthesis highlighted correctly. The closing parens are inverted from what they should be.
![screen shot 2015-12-07 at 5 22 19 pm](https://cloud.githubusercontent.com/assets/87665/11641603/200e73fa-9d07-11e5-8764-94dfe1741cea.png)
This is a very common way to define callback functions in Node.

**Comment by luochen1990** [comment]
You are using some other plugin which hilighted parentheses itself, which result in a conflict.

To solve this problem, you must **figure out which plugin cause this problem**.

The simplest way to solve this problem is disable one of them.

And if you want to fixup it via a perfect but hard way, you must:

1. Figure out what the evil plugin did. You can use vim command `:syntax` or read the plugins document (or code) to check out which syntax definition is added.
2. Think about what style is what you really want to have. and choose to disable the syntax rule from the evil plugin or include it with rainbow together somehow.
3. If you decide to include it with rainbow, then you should learn about the advanced configuration of rainbow and add a configuration specially for javascript filetype.

**Comment by meuserj** [comment]
Thanks for the tip, I have identify the evil plugin I was using.
